---

- name: "Install PostgreSQL"
  package: name={{ item }} state=present
  with_items:
    - postgresql-server
    - postgresql-contrib

- name: "Initiate database"
  command: postgresql-setup initdb
           creates=/var/lib/pgsql/data/postgresql.conf

- name: "Ensure PostgreSQL is enabled and started"
  service: name=postgresql enabled=yes state=started

- name: "Set authentication to md5 for local connections (IPv4)"
  lineinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    regexp: 'host\s+all\s+all\s+127.0.0.1/32'
    line: 'host all all 127.0.0.1/32 md5'
  notify: Restart PostgreSQL

- name: "Set authentication to md5 for local connections (IPv6)"
  lineinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    regexp: 'host\s+all\s+all\s+::1/128'
    line: 'host all all ::1/128 md5'
  notify: Restart PostgreSQL
